Repository sulu/SuluFormBundle, pull requests merged in 2019-05, with the labels that each got.

#189 Fix travis mysql service
  .travis.yml
  CHANGELOG.md
Labels: bug

#188 Add plain text variant for email
  CHANGELOG.md
  Configuration/FormConfigurationFactory.php
  Configuration/MailConfiguration.php
  Configuration/MailConfigurationInterface.php
  DependencyInjection/Configuration.php
  DependencyInjection/SuluFormExtension.php
  Form/Handler.php
  Mail/Helper.php
  Mail/HelperInterface.php
  Mail/NullHelper.php
  Resources/config/services.xml
  Resources/doc/dynamic.md
  Resources/translations/messages.de.xliff
  Resources/translations/messages.en.xliff
  Resources/translations/messages.fr.xliff
  Resources/translations/messages.nl.xliff
  Resources/views/mails/customer_plain_text.html.twig
  Resources/views/mails/notify_plain_text.html.twig
  Tests/Unit/Configuration/FormConfigurationFactoryTest.php
Labels: feature

#157 Add reference store to form bundle
  CHANGELOG.md
  Content/Types/FormSelect.php
  Event/CacheInvalidationListener.php
  Manager/FormManager.php
  Resources/config/services.xml
  UPGRADE.md
Labels: enhancement
