Repository sulu/SuluFormBundle, pull requests merged in 2020-02, with the labels that each got.

#225 Add priority and check for existing view
  Admin/DynamicListAdmin.php
Labels: bug

#224 Fix CacheInvalidator and some type issues and increase phpstan to 5
  Configuration/FormConfigurationFactory.php
  Content/Types/SingleFormSelection.php
  Controller/DynamicController.php
  Dynamic/Checksum.php
  Entity/Dynamic.php
  Entity/FormTranslation.php
  Event/CacheInvalidationListener.php
  Exception/FormNotFoundException.php
  ListBuilder/DynamicListBuilder.php
  ListBuilder/DynamicListFactory.php
  Manager/FormManager.php
  Media/CollectionStrategyInterface.php
  Media/CollectionStrategySingle.php
  Media/CollectionStrategyTree.php
  Resources/config/services.xml
  Tests/Functional/Controller/FormControllerTest.php
  Tests/Functional/Metadata/DynamicListMetadataLoaderTest.php
  TitleProvider/StructureTitleProvider.php
  phpstan.neon
Labels: bug, enhancement

#216 #194 Add sender the same as parameter for Sender-header on envelope
  DependencyInjection/Configuration.php
  DependencyInjection/SuluFormExtension.php
  Mail/Helper.php
  Resources/config/services.xml
  Resources/doc/index.md
Labels: feature
