Repository sulu/SuluFormBundle, pull requests merged in 2020-04, with the labels that each got.

#237 Rename package to sulu/form-bundle
  Resources/doc/index.md
  composer.json
Labels: enhancement

#239 Fix templating variable
  Form/Handler.php
Labels: bug

#215 Fix line breaks in notify emails
  CHANGELOG.md
  Resources/views/mails/notify.html.twig
Labels: bug

#240 Adjust FormWebsiteController reference in dynamic template
  Resources/views/themes/dynamic.html.twig
Labels: bug

#217 Add FormGeneratorCommand
  .travis.yml
  Command/FormGeneratorCommand.php
  DependencyInjection/SuluFormExtension.php
  Entity/Form.php
  Entity/FormField.php
  Resources/config/doctrine/Form.orm.xml
  Resources/config/doctrine/FormField.orm.xml
  Resources/config/services.xml
  Resources/doc/dynamic.md
  Tests/Functional/Controller/FormControllerTest.php
  composer.json
Labels: feature

#218 Add possibility for a honeypot field
  .travis.yml
  Configuration/FormConfigurationFactory.php
  DependencyInjection/Configuration.php
  DependencyInjection/SuluFormExtension.php
  Form/Handler.php
  Form/HandlerInterface.php
  Form/Type/DynamicFormType.php
  Resources/config/services.xml
  Resources/doc/dynamic.md
Labels: feature

#241 Remove paragraphs from labels
  Entity/FormFieldTranslation.php
Labels: bug

#244 Fix/radio options cant edit
  Controller/FormController.php
Labels: bug

#246 Add improved basic theme
  Command/FormGeneratorCommand.php
  Dynamic/Types/FreeTextType.php
  Dynamic/Types/HeadlineType.php
  Dynamic/Types/RadioButtonsType.php
  Dynamic/Types/SpacerType.php
  Entity/FormTranslation.php
  Resources/doc/csrf.md
  Resources/doc/dynamic.md
  Resources/doc/theming.md
  Resources/views/themes/basic.html.twig
  Resources/views/themes/dynamic.html.twig
Labels: feature
