Repository sulu/SuluFormBundle, pull requests merged in 2024-04, with the labels that each got.

#362 Added hidden field
  Dynamic/Types/HiddenType.php
  Entity/Dynamic.php
  Resources/config/form-fields/field_hidden.xml
  Resources/config/types.xml
  Resources/translations/admin.de.json
  Resources/translations/admin.en.json
  Tests/Functional/Metadata/DynamicFormMetadataLoaderTest.php
Labels: feature

#360 Fix DynamicController dynamicListFactory build arguments order
  Controller/DynamicController.php
Labels: bug

#328 Fix file type attr
  Dynamic/Types/AttachmentType.php
  UPGRADE.md
Labels: enhancement
